services:
  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./srcs/requirements/nginx/html:/var/www/html
      - ./srcs/requirements/nginx/ssl:/etc/nginx/ssl
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: on-failure
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure
    env_file:
      - .env

  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: on-failure
    env_file:
      - .env

volumes:
  mariadb_data:

networks:
  inception_network:
    driver: bridge
