version: '3.8'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
      - ./requirements/nginx/ssl:/etc/ssl/private
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always
 
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
 
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_volume:/var/lib/mysql
      - ./requirements/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inception_network

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mohrahma/data/mariadb
  wordpress_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mohrahma/data/wordpress

networks:
  inception_network:
    driver: bridge
