services:
  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: on-failure
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure
    env_file:
      - .env

  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: on-failure
    env_file:
      - .env

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/mohrahma/data/mariadb"
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/mohrahma/data/wordpress"

networks:
  inception_network:
    driver: bridge
