services:
  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: on-failure
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    ports:
       - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure
    env_file:
      - .env
    secrets:
      - mysql_password

  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: on-failure
    env_file:
      - .env
    secrets:
      - mysql_password
      - wordpress_user_password
      - wordpress_root_password

secrets:
  mysql_password:
    file: ./../secrets/credentials.txt
  wordpress_user_password:
    file: ./../secrets/db_password.txt
  wordpress_root_password:
    file: ./../secrets/db_root_password.txt

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/mohrahma/data/mariadb"
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/mohrahma/data/wordpress"

networks:
  inception_network:
    driver: bridge
