services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped

networks:
  inception_network:
    driver: bridge
